padre('jesus','tere').
padre('jesus','ester').
padre('tere','tere').
padre('tere','ester').
padre('tere','gil').
padre('tere','fernando').
padre('tere','jhon').
padre('tere','victor').
padre('ignacio','tere').
padre('ignacio','gil').
padre('ignacio','fernando').
padre('ignacio','jhon').
padre('ignacio','victor').
padre('ester','jose').
padre('ester','roberto').
padre('jose','jose').
padre('jose','roberto').
mujer('ester').
mujer('tere').

hermano(A,B):-padre('tere',A),padre('ignacio',B),A\=B.
hijas(A):-padre('jesus',A),padre('tere',A),mujer(A),A\='tere'.
abuelos(A):-padre(A,'tere'),padre(A,'ester').
primos(A):-padre('ester',A),padre('jose',A).
tios(A):-padre(A,'jose'),A\='ester'.